### ISSUE TITLE
URL in Installation instructions returns 404

### ISSUE THREAD

**Issue by madonius** [redBorder/redborder-manager#13]
Executing the installation instructions as described in the [readme](https://github.com/redBorder/redborder-manager/blob/master/README.md) Returns a 404 in the URL
```bash
[root@localhost ~]# wget http://repo.redborder.com/redborder-repo-1.0.0-1.el7.rb.noarch.rpm
--2018-01-22 15:37:56--  http://repo.redborder.com/redborder-repo-1.0.0-1.el7.rb.noarch.rpm
Resolving repo.redborder.com (repo.redborder.com)... 52.218.21.52
Connecting to repo.redborder.com (repo.redborder.com)|52.218.21.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-22 15:37:59 ERROR 404: Not Found.
```

**Comment by jjptapia** [comment]
Hi madonius, it is an error in README.md, thanks for the issue. I have fixed now.
You can see that correct versions for redborder-repo package are in:

https://github.com/redBorder/redborder-repo/releases

Please, try now with this instructions:

`# yum install epel-release && rpm -ivh http://repo.redborder.com/redborder-repo-0.0.3-1.el7.rb.noarch.rpm`

Best regards.
